version: "3.5"
services:
  api:
    build: .
    container_name: api
    hostname: api
    image: api
    ports:
      - 8000:8000
    environment:
      LOG_LEVEL: "info"
      UVICORN_LOG_LEVEL: "debug"
      UVICORN_WORKERS: "4"
      NEW_RELIC_ENABLED: ""
      NEW_RELIC_APP_NAME: ""
      NEW_RELIC_LICENSE_KEY: ""